// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class ActividadImagen
    {
        public int Id { get; set; }
        public string CodEntidad { get; set; }
        public string Imagen { get; set; }
        public string Detalle { get; set; }
        public string Ccia { get; set; }
        public string IdGrupo { get; set; }
        public string IdProyecto { get; set; }
        public DateTime? FecCrea { get; set; }
        public string CodRegistroActividad { get; set; }
    }
}