// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class Alumno
    {
        public string AlumnoNombre { get; set; }
        public string CodAlumno { get; set; }
        public string FechaCreacion { get; set; }
        public string FechaMod { get; set; }
        public string Cedula { get; set; }
        public int? Edad { get; set; }
        public string CorreoInstitucional { get; set; }
        public string CorreoPersonal { get; set; }
        public string CodFacultad { get; set; }
        public string CodCarrera { get; set; }
        public string SemestreNivel { get; set; }
        public string IdCanton { get; set; }
        public string IdProvincia { get; set; }
        public string Direccion { get; set; }
        public string TelefonoCelular { get; set; }
        public string TelefonoCasa { get; set; }
        public string CodCia { get; set; }
        public string CodSexo { get; set; }
        public string CodCurso { get; set; }
        public string Capacidades { get; set; }
    }
}