// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class Asignproyprocess
    {
        public int Id { get; set; }
        public string CodCoordgeneral { get; set; }
        public string CodContraparte { get; set; }
        public string CodProy { get; set; }
        public string CodProceso { get; set; }
    }
}