// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class AsignModUser
    {
        public string CodUser { get; set; }
        public string CodMod { get; set; }
        public int? State { get; set; }
        public string CodCia { get; set; }
    }
}