// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class Auditoria
    {
        public string CodAuditoria { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string IdUser { get; set; }
        public string IdInstituto { get; set; }
        public DateTime FecAudit { get; set; }
    }
}