// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class BeneficiariosVinculacion
    {
        public string CedBeneficiario { get; set; }
        public string NombreBeneficiario { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
        public string IdCanton { get; set; }
        public int? Edad { get; set; }
        public string CedRepresentante { get; set; }
        public string IdJornada { get; set; }
        public string Tema1 { get; set; }
        public string Tema2 { get; set; }
        public string Tema3 { get; set; }
        public string IdUserRegister { get; set; }
        public string IdProcesos { get; set; }
        public string IdProyecto { get; set; }
        public string InstitucionNombre { get; set; }
        public string Ccia { get; set; }
        public string CodDay1 { get; set; }
        public string CodDay2 { get; set; }
        public string CedulaBeneficiario { get; set; }
        public string CodSexo { get; set; }
        public string TelfCelular { get; set; }
    }
}