// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class ConfDom
    {
        public int Id { get; set; }
        public string ObjecDom { get; set; }
        public bool? Disabled { get; set; }
        public bool? Show { get; set; }
        public string UserCod { get; set; }
        public int? Tiempo { get; set; }
    }
}