// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class ConvenioEspecifico
    {
        public string CodConvenioEsp { get; set; }
        public string NombreConvenio { get; set; }
        public string NombreInstitucionConvenio { get; set; }
        public DateTime? Finicio { get; set; }
        public DateTime? Ffin { get; set; }
        public string CodConvenioMarco { get; set; }
        public DateTime? FechModif { get; set; }
        public string IdEstado { get; set; }
    }
}