// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class ConvenioMarco
    {
        public string NombreConvenio { get; set; }
        public string IdCia { get; set; }
        public string RepresentanteConvenioU { get; set; }
        public string RepresentanteConvenioI { get; set; }
        public string CodConvenioMarco { get; set; }
        public string NombreConvenioIntitu { get; set; }
        public string IdentificadorUnicoUniversidad { get; set; }
        public DateTime? FechModif { get; set; }
        public DateTime? FechaIni { get; set; }
        public DateTime? Fachafin { get; set; }
        public string IdEstado { get; set; }
    }
}