// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class CreateAccountResult
    {
        public string message_server { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
    }
}
