// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class FileApp
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Ruta { get; set; }
    }
}