// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class GenerarProyecto
    {
        public string IdProyecto { get; set; }
        public string NombreProyecto { get; set; }
        public DateTime? Finicio { get; set; }
        public DateTime? Ffin { get; set; }
        public string AreaDesarrollo { get; set; }
        public string IdTutor { get; set; }
        public string ProyectoProveniente { get; set; }
        public string DirectorProyecto { get; set; }
        public string DescripcionProyecto { get; set; }
        public int? Horas { get; set; }
        public string Alias { get; set; }
    }
}