// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class GrupoEstudiante
    {
        public string CodGrupo { get; set; }
        public string NombreGrupo { get; set; }
        public string IdEstudiante { get; set; }
        public string Codcia { get; set; }
        public DateTime FecCrea { get; set; }
        public int Id { get; set; }
    }
}