// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class Imagen
    {
        public string IdImagen { get; set; }
        public string Tipo { get; set; }
        public string ImagenContent { get; set; }
    }
}