// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class Instituto
    {
        public string Codcia { get; set; }
        public string Ruc { get; set; }
        public string Correo { get; set; }
        public string Cta1 { get; set; }
        public string Cta2 { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int? TelefA { get; set; }
        public int? TelfB { get; set; }
        public int? TelfC { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Direccion { get; set; }
        public DateTime FecCrea { get; set; }
        public string Web { get; set; }
        public int? HorasVinc { get; set; }
        public string CodProvincia { get; set; }
        public string CodCanton { get; set; }
        public DateTime? FechaFundacion { get; set; }
    }
}