// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class LandingConfiguration
    {
        public int Id { get; set; }
        public string TituloTema { get; set; }
        public string BackgroundLanding { get; set; }
        public string Logotipo { get; set; }
        public string FormularioFondo { get; set; }
        public string FormularioColorLetras { get; set; }
        public string BotonIngresoFondo { get; set; }
        public string BotonIngresoColorLetras { get; set; }
        public string BordeLateralColor { get; set; }
        public bool? EstadoMatriculaRegistro { get; set; }
        public string CodInstituto { get; set; }
        public string TituloLanding { get; set; }
        public string BackgroundImgLanding { get; set; }
    }
}