// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class MaestroInstitucion
    {
        public string CodInstiProy { get; set; }
        public string NombreInstituto { get; set; }
        public string Alias { get; set; }
        public string IdProvincia { get; set; }
        public string IdCanton { get; set; }
        public string Direccion { get; set; }
        public string TelefonoCelular { get; set; }
        public string Email { get; set; }
        public string TipoInsti { get; set; }
        public string Telefono { get; set; }
        public string Codcia { get; set; }
    }
}