// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class ObtenerAlumnoRegistrosResult
    {
        public string numeroProceso { get; set; }
        public string idProcesos { get; set; }
        public string idProyecto { get; set; }
        public string nombreProyecto { get; set; }
        public DateTime fecCrea { get; set; }
        public string codGrupo { get; set; }
        public string nombreGrupo { get; set; }
        public int? horas { get; set; }
        public string codioCapacidad { get; set; }
        public string capacidades { get; set; }
        public string codigo { get; set; }
        public DateTime? fecInicio { get; set; }
        public DateTime? fecFin { get; set; }
        public string alumnoNombre { get; set; }
        public string codCarrera { get; set; }
        public string idCoordinadorGeneral { get; set; }
        public string personaNombre { get; set; }
        public string cedula { get; set; }
        public string nombreInstituto { get; set; }
        public string tipoInsti { get; set; }
        public string codInstiProy { get; set; }
        public string carreraNombre { get; set; }
        public string codFacultad { get; set; }
        public string nombreFacultad { get; set; }
        public string idProvincia { get; set; }
        public string provinicaInstituto { get; set; }
    }
}
