// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class ObtenerAlumnosResult
    {
        public string alumnoNombre { get; set; }
        public string codAlumno { get; set; }
        public string cedula { get; set; }
        public string codCarrera { get; set; }
        public string fechaCreacion { get; set; }
        public string idProvincia { get; set; }
        public string idCanton { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public string codSexo { get; set; }
        public string carrera { get; set; }
        public string facultad { get; set; }
        public string codCapacidades { get; set; }
        public string codFacultad { get; set; }
        public string codCurso { get; set; }
        public string nombreCurso { get; set; }
        public string capacidades { get; set; }
        public string codigo { get; set; }
        public string correoInstitucional { get; set; }
        public string direccion { get; set; }
        public int? edad { get; set; }
        public string semestreNivel { get; set; }
        public string telefonoCelular { get; set; }
        public string telefonoCasa { get; set; }
    }
}
