// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class ObtenerRegistrosActividadesResult
    {
        public string codRegActivity { get; set; }
        public string nombre { get; set; }
        public string nombreActivity { get; set; }
        public string descriptionActivity { get; set; }
        public DateTime? fecCreacion { get; set; }
        public string idProceso { get; set; }
        public int? horas { get; set; }
    }
}
