// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class ObtenerProcesosResult
    {
        public string Decano { get; set; }
        public string CoordinadorGeneral { get; set; }
        public DateTime? fecInicio { get; set; }
        public DateTime? fecFin { get; set; }
        public string Tutor { get; set; }
        public string nombreGrupo { get; set; }
        public int? cantidadRegistrados { get; set; }
        public string numeroProceso { get; set; }
        public DateTime? feccrea { get; set; }
        public int? horas { get; set; }
        public string idProcesos { get; set; }
        public string idTutorVinculacion { get; set; }
        public string idDecanoVinculacion { get; set; }
        public string idCoordinadorGeneral { get; set; }
        public string idAlumno { get; set; }
        public string idProyecto { get; set; }
        public string nombreProyecto { get; set; }
    }
}
