// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class ObtenerGrupoAlumnoResult
    {
        public string codGrupo { get; set; }
        public string nombreGrupo { get; set; }
        public string idEstudiante { get; set; }
        public string capacidades { get; set; }
        public string codigo { get; set; }
        public string alumnoNombre { get; set; }
        public string cedula { get; set; }
        public string codcia { get; set; }
        public DateTime fecCrea { get; set; }
        public int id { get; set; }
    }
}
