// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class ObtenerProyectosResult
    {
        public string nombreConvenioEsp { get; set; }
        public string alias { get; set; }
        public string nombreConvenioEspInstitu { get; set; }
        public string idProyecto { get; set; }
        public string nombreConvenioMarco { get; set; }
        public string nombreConvenioMarcoIntitu { get; set; }
        public string idTutor { get; set; }
        public string nombreProyecto { get; set; }
        public string tutor { get; set; }
        public int? horas { get; set; }
        public string codecEsp { get; set; }
        public string idDirectorProyecto { get; set; }
        public string directorProyecto { get; set; }
        public DateTime? finicio { get; set; }
        public DateTime? ffin { get; set; }
        public string areaDesarrollo { get; set; }
        public string descripcionProyecto { get; set; }
    }
}
