// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class ObtenerEntidadesResult
    {
        public string nombrefacultad { get; set; }
        public string codFacultad { get; set; }
        public string codCarrera { get; set; }
        public string alumnoNombre { get; set; }
        public string nombreCarrera { get; set; }
        public string idProvincia { get; set; }
        public string nombreProvincia { get; set; }
        public string idCanton { get; set; }
        public string nombreCanton { get; set; }
        public string capacidades { get; set; }
        public string codCapacidades { get; set; }
        public string codSexo { get; set; }
        public string nombreSexo { get; set; }
        public string cedula { get; set; }
        public string correoInstitucional { get; set; }
        public string correoPersonal { get; set; }
        public string direccion { get; set; }
        public int? edad { get; set; }
        public string fechaCreacion { get; set; }
        public string fechaMod { get; set; }
        public string semestreNivel { get; set; }
        public int? telefonoCasa { get; set; }
        public string telefonoCelular { get; set; }
        public string codCurso { get; set; }
        public string nombreCurso { get; set; }
    }
}
