// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class ObtenerConveniosResult
    {
        public int? cantidadConvEsp { get; set; }
        public string nombreConvenio { get; set; }
        public string idCia { get; set; }
        public string representanteConvenioI { get; set; }
        public string representanteConvenioU { get; set; }
        public string codConvenioMarco { get; set; }
        public string nombreConvenioIntitu { get; set; }
        public string identificadorUnicoUniversidad { get; set; }
        public DateTime? fechModif { get; set; }
        public DateTime? fechaIni { get; set; }
        public DateTime? fachafin { get; set; }
        public string idEstado { get; set; }
        public string nombreEstado { get; set; }
    }
}
