// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{
    public partial class ObtenerInstitutosResult
    {
        public string codInstiProy { get; set; }
        public string nombreInstituto { get; set; }
        public string alias { get; set; }
        public string idProvincia { get; set; }
        public string provincia { get; set; }
        public string idCanton { get; set; }
        public string canton { get; set; }
        public string direccion { get; set; }
        public string telefonoCelular { get; set; }
        public string email { get; set; }
        public string tipoInsti { get; set; }
        public string tipoIntituto { get; set; }
        public string telefono { get; set; }
    }
}
