// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class Procesos
    {
        public string IdProcesos { get; set; }
        public string NumeroProceso { get; set; }
        public string IdDecanoVinculacion { get; set; }
        public string IdTutorVinculacion { get; set; }
        public string IdCoordinadorGeneral { get; set; }
        public string IdAlumno { get; set; }
        public DateTime? FeccreaProceso { get; set; }
        public string Idcia { get; set; }
        public string IdProyecto { get; set; }
        public int? Horas { get; set; }
        public DateTime? FecInicio { get; set; }
        public DateTime? FecFin { get; set; }
    }
}