// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class RegistroActividad
    {
        public string CodRegActivity { get; set; }
        public string NombreActivity { get; set; }
        public string DescriptionActivity { get; set; }
        public DateTime? FecCreacion { get; set; }
        public string Ccia { get; set; }
        public string IdProyecto { get; set; }
        public string IdProceso { get; set; }
        public TimeSpan? HoraIni { get; set; }
        public TimeSpan? HoraFin { get; set; }
        public string Observaciones { get; set; }
        public string IdUser { get; set; }
        public string IdGrupo { get; set; }
        public int? Horas { get; set; }
    }
}