// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class VinculacionConfig
    {
        public int Id { get; set; }
        public bool? InscriVin { get; set; }
        public string NombreInscrip { get; set; }
        public string CodGrupo { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public string Codcia { get; set; }
        public string CodAdmin { get; set; }
        public string CodProceso { get; set; }
    }
}