// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class WebUser
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string UserCod { get; set; }
        public string Email { get; set; }
        public string Tipo { get; set; }
        public string NombreEntidad { get; set; }
    }
}